# Generated by Django 4.1.2 on 2022-10-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KD_KABUPATEN', models.CharField(max_length=4, unique=True)),
                ('KABUPATEN', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KD_KECAMATAN', models.CharField(max_length=8, unique=True)),
                ('KECAMATAN', models.CharField(max_length=100)),
                ('KD_KABUPATEN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kabupaten')),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KD_PROVINSI', models.CharField(max_length=2, unique=True)),
                ('PROVINSI', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KD_PUSKESMAS', models.CharField(max_length=11, unique=True)),
                ('PUSKESMAS', models.CharField(max_length=60)),
                ('ALAMAT', models.CharField(max_length=100)),
                ('KD_KECAMATAN', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.kecamatan')),
            ],
        ),
        migrations.AddField(
            model_name='kabupaten',
            name='KD_PROVINSI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provinsi'),
        ),
    ]
